In [32]:
movies=pd.read_csv('tmdb_5000_movies.csv')
credits=pd.read_csv('tmdb_5000_credits.csv')

In [33]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [34]:
credits.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [35]:
movies = pd.read_csv('tmdb_5000_movies.csv')
movies = movies.merge(credits, on='title')

In [36]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [37]:
#genres
#id
#keywords
#title
#overview
#cast
#crew
movies=movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [38]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4809 non-null   int64
 1   title     4809 non-null   object
 2   overview  4806 non-null   object
 3   genres    4809 non-null   object
 4   keywords  4809 non-null   object
 5   cast      4809 non-null   object
 6   crew      4809 non-null   object
dtypes: int64(1), object(6)
memory usage: 263.1+ KB

In [39]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [40]:
movies.dropna(inplace=True)

In [41]:
movies.duplicated().sum()

np.int64(0)

In [42]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [43]:
def convert(obj):
    L=[]
    counter=0
    for i in ast.literal_eval(obj):
        if counter<3:
            L.append(i['name'])
            counter+=1
    return L

In [44]:
import ast

movies['genres'] = movies['genres'].apply(convert)

In [45]:
movies['keywords']= movies['keywords'].apply(convert)

In [46]:
movies['cast']= movies['cast'].apply(convert)

In [47]:
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy]","[culture clash, future, space war]","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [48]:
def fetch_director(obj):
    L=[]
    for i in ast.literal_eval(obj):
        if i['job']=='Director':
            L.append(i['name'])
            break
    return L

In [31]:
movies['crew']= movies['crew'].apply(fetch_director)

In [49]:
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy]","[culture clash, future, space war]","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [50]:
movies['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [51]:
movies['overview']= movies['overview'].apply(lambda x:x.split())

In [52]:
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy]","[culture clash, future, space war]","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [57]:
movies['genres'] = movies['genres'].apply(lambda x: [i.replace(" ", "") for i in x])
movies['keywords'] = movies['keywords'].apply(lambda x: [i.replace(" ", "") for i in x])
movies['cast'] = movies['cast'].apply(lambda x: [i.replace(" ", "") for i in x])
movies['crew'] = movies['crew'].apply(lambda x: [i.replace(" ", "") for i in x])

movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [58]:
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy]","[cultureclash, future, spacewar]","[SamWorthington, ZoeSaldana, SigourneyWeaver]","[[, {, "", c, r, e, d, i, t, _, i, d, "", :, , ""...","[In, the, 22nd, century,, a, paraplegic, Marin..."

In [59]:
new_df=movies[['movie_id','title','tags']]

In [61]:
new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))

C:\Users\VENKATA PAVANI\AppData\Local\Temp\ipykernel_14052\1824047427.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))

In [63]:
new_df.head(1)

   movie_id   title                                               tags
0     19995  Avatar  I n   t h e   2 2 n d   c e n t u r y ,   a   ...

In [65]:
new_df['tags'] = new_df['tags'].apply(lambda x: x.lower())

C:\Users\VENKATA PAVANI\AppData\Local\Temp\ipykernel_14052\1380776331.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x: x.lower())

In [67]:
new_df.head(1)

   movie_id   title                                               tags
0     19995  Avatar  i n   t h e   2 2 n d   c e n t u r y ,   a   ...

In [69]:
new_df['tags'][0]

'i n   t h e   2 2 n d   c e n t u r y ,   a   p a r a p l e g i c   m a r i n e   i s   d i s p a t c h e d   t o   t h e   m o o n   p a n d o r a   o n   a   u n i q u e   m i s s i o n ,   b u t   b e c o m e s   t o r n   b e t w e e n   f o l l o w i n g   o r d e r s   a n d   p r o t e c t i n g   a n   a l i e n   c i v i l i z a t i o n .   a c t i o n   a d v e n t u r e   f a n t a s y   c u l t u r e c l a s h   f u t u r e   s p a c e w a r   s a m w o r t h i n g t o n   z o e s a l d a n a   s i g o u r n e y w e a v e r   [   {   "   c   r   e   d   i   t   _   i   d   "   :     "   5   2   f   e   4   8   0   0   9   2   5   1   4   1   6   c   7   5   0   a   c   a   2   3   "   ,     "   d   e   p   a   r   t   m   e   n   t   "   :     "   e   d   i   t   i   n   g   "   ,     "   g   e   n   d   e   r   "   :     0   ,     "   i   d   "   :     1   7   2   1   ,     "   j   o   b   "   :     "   e   d   i   t   o   r   "   ,     "   n   a   m   e   "   :     "   s   t   e   p   h   e   n     e   .     r   i   v   k   i   n   "   }   ,     {   "   c   r   e   d   i   t   _   i   d   "   :     "   5   3   9   c   4   7   e   c   c   3   a   3   6   8   1   0   e   3   0   0   1   f   8   7   "   ,     "   d   e   p   a   r   t   m   e   n   t   "   :     "   a   r   t   "   ,     "   g   e   n   d   e   r   "   :     2   ,     "   i   d   "   :     4   9   6   ,     "   j   o   b   "   :     "   p   r   o   d   u   c   t   i   o   n     d   e   s   i   g   n   "   ,     "   n   a   m   e   "   :     "   r   i   c   k     c   a   r   t   e   r   "   }   ,     {   "   c   r   e   d   i   t   _   i   d   "   :     "   5   4   4   9   1   c   8   9   c   3   a   3   6   8   0   f   b   4   0   0   1   c   f   7   "   ,     "   d   e   p   a   r   t   m   e   n   t   "   :     "   s   o   u   n   d   "   ,     "   g   e   n   d   e   r   "   :     0   ,     "   i   d   "   :     9   0   0   ,     "   j   o   b   "   :     "   s   o   u   n   d     d   e   s   i   g   n   e   r   "   ,     "   n   a   m   e   "   :     "   c   h   r   i   s   t   o   p   h   e   r     b   o   y   e   s   "   }   ,     {   "   c   r   e   d   i   t   _   i   d   "   :     "   5   4   4   9   1   c   b   7   0   e   0   a   2   6   7   4   8   0   0   0   1   b   d   0   "   ,     "   d   e   p   a   r   t   m   e   n   t   "   :     "   s   o   u   n   d   "   ,     "   g   e   n   d   e   r   "   :     0   ,     "   i   d   "   :     9   0   0   ,     "   j   o   b   "   :     "   s   u   p   e   r   v   i   s   i   n   g     s   o   u   n   d     e   d   i   t   o   r   "   ,     "   n   a   m   e   "   :     "   c   h   r   i   s   t   o   p   h   e   r     b   o   y   e   s   "   }   ,     {   "   c   r   e   d   i   t   _   i   d   "   :     "   5   3   9   c   4   a   4   c   c   3   a   3   6   8   1   0   c   9   0   0   2   1   0   1   "   ,     "   d   e   p   a   r   t   m   e   n   t   "   :     "   p   r   o   d   u   c   t   i   o   n   "   ,     "   g   e   n   d   e   r   "   :     1   ,     "   i   d   "   :     1   2   6   2   ,     "   j   o   b   "   :     "   c   a   s   t   i   n   g   "   ,     "   n   a   m   e   "   :     "   m   a   l   i     f   i   n   n   "   }   ,     {   "   c   r   e   d   i   t   _   i   d   "   :     "   5   5   4   4   e   e   3   b   9   2   5   1   4   1   4   9   9   f   0   0   0   8   f   c   "   ,     "   d   e   p   a   r   t   m   e   n   t   "   :     "   s   o   u   n   d   "   ,     "   g   e   n   d   e   r   "   :     2   ,     "   i   d   "   :     1   7   2   9   ,     "   j   o   b   "   :     "   o   r   i   g   i   n   a   l     m   u   s   i   c     c   o   m   p   o   s   e   r   "   ,     "   n   a   m   e   "   :     "   j   a   m   e   s     h   o   r   n   e   r   "   }   ,     {   "   c   r   e   d   i   t   _   i   d   "   :     "   5   2   f   e   4   8   0   0   9   2   5   1   4   1   6   c   7   5   0   a   c   9   c   3   "   ,     "   d   e   p   a   r   t   m   e   n   t   "   :     "   d   i   r   e   c   t   i   n   g   "   ,     "   g   e   n   d   e   r   "   :     2   ,     "   i   d   "   :     2   7   1   0   ,     "   j   o   b   "   :     "   d   i   r   e   c   t   o   r   "   ,     "   n   a   m   e   "   :     "   j   a   m   e   s     c   a   m   e   r   o   n   "   }   ,     {   "   c   r   e   d   i   t   _   i   d   "   :     "   5   2   f   e   4   8   0   0   9   2   5   1   4   1   6   c   7   5   0   a   c   9   d   9   "   ,     "   d   e   p   a   r   t   m   e   n   t   "   :     "   w   r   i   t   i   n   g   "   ,     "   g   e   n   d   e   r   "   :     2   ,     "   i   d   "   :     2   7   1   0   ,     "   j   o   b   "   :     "   w   r   i   t   e   r   "   ,     "   n   a   m   e   "   :     "   j   a   m   e   s     c   a   m   e   r   o   n   "   }   ,     {   "   c   r   e   d   i   t   _   i   d   "   :     "   5   2   f   e   4   8   0   0   9   2   5   1   4   1   6   c   7   5   0   a   c   a   1   7   "   ,     "   d   e   p   a   r   t   m   e   n   t   "   :     "   e   d   i   t   i   n   g   "   ,     "   g   e   n   d   e   r   "   :     2   ,     "   i   d   "   :     2   7   1   0   ,     "   j   o   b   "   :     "   e   d   i   t   o   r   "   ,     "   n   a   m   e   "   :     "   j   a   m   e   s     c   a   m   e   r   o   n   "   }   ,     {   "   c   r   e   d   i   t   _   i   d   "   :     "   5   2   f   e   4   8   0   0   9   2   5   1   4   1   6   c   7   5   0   a   c   a   2   9   "   ,     "   d   e   p   a   r   t   m   e   n   t   "   :     "   p   r   o   d   u   c   t   i   o   n   "   ,     "   g   e   n   d   e   r   "   :     2   ,     "   i   d   "   :     2   7   1   0   ,     "   j   o   b   "   :     "   p   r   o   d   u   c   e   r   "   ,     "   n   a   m   e   "   :     "   j   a   m   e   s     c   a   m   e   r   o   n   "   }   ,     {   "   c   r   e   d   i   t   _   i   d   "   :     "   5   2   f   e   4   8   0   0   9   2   5   1   4   1   6   c   7   5   0   a   c   a   3   f   "   ,     "   d   e   p   a   r   t   m   e   n   t   "   :     "   w   r   i   t   i   n   g   "   ,     "   g   e   n   d   e   r   "   :     2   ,     "   i   d   "   :     2   7   1   0   ,     "   j   o   b   "   :     "   s   c   r   e   e   n   p   l   a   y   "   ,     "   n   a   m   e   "   :     "   j   a   m   e   s     c   a   m   e   r   o   n   "   }   ,     {   "   c   r   e   d   i   t   _   i   d   "   :     "   5   3   9   c   4   9   8   7   c   3   a   3   6   8   1   0   b   a   0   0   2   1   a   4   "   ,     "   d   e   p   a   r   t   m   e   n   t   "   :     "   a   r   t   "   ,     "   g   e   n   d   e   r   "   :     2   ,     "   i   d   "   :     7   2   3   6   ,     "   j   o   b   "   :     "   a   r   t     d   i   r   e   c   t   i   o   n   "   ,     "   n   a   m   e   "   :     "   a   n   d   r   e   w     m   e   n   z   i   e   s   "   }   ,     {   "   c   r   e   d   i   t   _   i   d   "   :     "   5   4   9   5   9   8   c   3   c   3   a   3   6   8   6   a   e   9   0   0   4   3   8   3   "   ,     "   d   e   p   a   r   t   m   e   n   t   "   :     "   v   i   s   u   a   l     e   f   f   e   c   t   s   "   ,     "   g   e   n   d   e   r   "   :     0   ,     "   i   d   "   :     6   6   9   0   ,     "   j   o   b   "   :     "   v   i   s   u   a   l     e   f   f   e   c   t   s     p   r   o   d   u   c   e   r   "   ,     "   n   a   m   e   "   :     "   j   i   l   l     b   r   o   o   k   s   "   }   ,     {   "   c   r   e   d   i   t   _   i   d   "   :     "   5   2   f   e   4   8   0   0   9   2   5   1   4   1   6   c   7   5   0   a   c   a   4   b   "   ,     "   d   e   p   a   r   t   m   e   n   t   "   :     "   p   r   o   d   u   c   t   i   o   n   "   ,     "   g   e   n   d   e   r   "   :     1   ,     "   i   d   "   :     6   3   4   7   ,     "   j   o   b   "   :     "   c   a   s   t   i   n   g   "   ,     "   n   a   m   e   "   :     "   m   a   r   g   e   r   y     s   i   m   k   i   n   "   }   ,     {   "   c   r   e   d   i   t   _   i   d   "   :     "   5   7   0   b   6   f   4   1   9   2   5   1   4   1   7   d   a   7   0   0   3   2   f   e   "   ,     "   d   e   p   a   r   t   m   e   n   t   "   :     "   a   r   t   "   ,     "   g   e   n   d   e   r   "   :     2   ,     "   i   d   "   :     6   8   7   8   ,     "   j   o   b   "   :     "   s   u   p   e   r   v   i   s   i   n   g     a   r   t     d   i   r   e   c   t   o   r   "   ,     "   n   a   m   e   "   :     "   k   e   v   i   n     i   s   h   i   o   k   a   "   }   ,     {   "   c   r   e   d   i   t   _   i   d   "   :     "   5   4   9   5   a   0   f   a   c   3   a   3   6   8   6   a   e   9   0   0   4   4   6   8   "   ,     "   d   e   p   a   r   t   m   e   n   t   "   :     "   s   o   u   n   d   "   ,     "   g   e   n   d   e   r   "   :     0   ,     "   i   d   "   :     6   8   8   3   ,     "   j   o   b   "   :     "   m   u   s   i   c     e   d   i   t   o   r   "   ,     "   n   a   m   e   "   :     "   d   i   c   k     b   e   r   n   s   t   e   i   n   "   }   ,     {   "   c   r   e   d   i   t   _   i   d   "   :     "   5   4   9   5   9   7   0   6   c   3   a   3   6   8   6   a   f   3   0   0   3   e   8   1   "   ,     "   d   e   p   a   r   t   m   e   n   t   "   :     "   s   o   u   n   d   "   ,     "   g   e   n   d   e   r   "   :     0   ,     "   i   d   "   :     8   1   5   9   ,     "   j   o   b   "   :     "   s   o   u   n   d     e   f   f   e   c   t   s     e   d   i   t   o   r   "   ,     "   n   a   m   e   "   :     "   s   h   a   n   n   o   n     m   i   l   l   s   "   }   ,     {   "   c   r   e   d   i   t   _   i   d   "   :     "   5   4   4   9   1   d   5   8   c   3   a   3   6   8   0   f   b   1   0   0   1   c   c   b   "   ,     "   d   e   p   a   r   t   m   e   n   t   "   :     "   s   o   u   n   d   "   ,     "   g   e   n   d   e   r   "   :     0   ,     "   i   d   "   :     8   1   6   0   ,     "   j   o   b   "   :     "   f   o   l   e   y   "   ,     "   n   a   m   e   "   :     "   d   e   n   n   i   e     t   h   o   r   p   e   "   }   ,     {   "   c   r   e   d   i   t   _   i   d   "   :     "   5   4   4   9   1   d   6   c   c   3   a   3   6   8   0   f   a   5   0   0   1   b   2   c   "   ,     "   d   e   p   a   r   t   m   e   n   t   "   :     "   s   o   u   n   d   "   ,     "   g   e   n   d   e   r   "   :     0   ,     "   i   d   "   :     8   1   6   3   ,     "   j   o   b   "   :     "   f   o   l   e   y   "   ,     "   n   a   m   e   "   :     "   j   a   n   a     v   a   n   c   e   "   }   ,     {   "   c   r   e   d   i   t   _   i   d   "   :     "   5   2   f   e   4   8   0   0   9   2   5   1   4   1   6   c   7   5   0   a   c   a   5   7   "   ,     "   d   e   p   a   r   t   m   e   n   t   "   :     "   c   o   s   t   u   m   e     &     m   a   k   e   -   u   p   "   ,     "   g   e   n   d   e   r   "   :     1   ,     "   i   d   "   :     8   5   2   7   ,     "   j   o   b   "   :     "   c   o   s   t   u   m   e     d   e   s   i   g   n   "   ,     "   n   a   m   e   "   :     "   d   e   b   o   r   a   h     l   y   n   n     s   c   o   t   t   "   }   ,     {   "   c   r   e   d   i   t   _   i   d   "   :     "   5   2   f   e   4   8   0   0   9   2   5   1   4   1   6   c   7   5   0   a   c   a   2   f   "   ,     "   d   e   p   a   r   t   m   e   n   t   "   :     "   p   r   o   d   u   c   t   i   o   n   "   ,     "   g   e   n   d   e   r   "   :     2   ,     "   i   d   "   :     8   5   2   9   ,     "   j   o   b   "   :     "   p   r   o   d   u   c   e   r   "   ,     "   n   a   m   e   "   :     "   j   o   n     l   a   n   d   a   u   "   }   ,     {   "   c   r   e   d   i   t   _   i   d   "   :     "   5   3   9   c   4   9   3   7   c   3   a   3   6   8   1   0   b   a   0   0   2   1   9   4   "   ,     "   d   e   p   a   r   t   m   e   n   t   "   :     "   a   r   t   "   ,     "   g   e   n   d   e   r   "   :     0   ,     "   i   d   "   :     9   6   1   8   ,     "   j   o   b   "   :     "   a   r   t     d   i   r   e   c   t   i   o   n   "   ,     "   n   a   m   e   "   :     "   s   e   a   n     h   a   w   o   r   t   h   "   }   ,     {   "   c   r   e   d   i   t   _   i   d   "   :     "   5   3   9   c   4   9   b   6   c   3   a   3   6   8   1   0   c   1   0   0   2   0   e   6   "   ,     "   d   e   p   a   r   t   m   e   n   t   "   :     "   a   r   t   "   ,     "   g   e   n   d   e   r   "   :     1   ,     "   i   d   "   :     1   2   6   5   3   ,     "   j   o   b   "   :     "   s   e   t     d   e   c   o   r   a   t   i   o   n   "   ,     "   n   a   m   e   "   :     "   k   i   m     s   i   n   c   l   a   i   r   "   }   ,     {   "   c   r   e   d   i   t   _   i   d   "   :     "   5   7   0   b   6   f   2   f   9   2   5   1   4   1   3   a   0   e   0   0   0   2   0   d   "   ,     "   d   e   p   a   r   t   m   e   n   t   "   :     "   a   r   t   "   ,     "   g   e   n   d   e   r   "   :     1   ,     "   i   d   "   :     1   2   6   5   3   ,     "   j   o   b   "   :     "   s   u   p   e   r   v   i   s   i   n   g     a   r   t     d   i   r   e   c   t   o   r   "   ,     "   n   a   m   e   "   :     "   k   i   m     s   i   n   c   l   a   i   r   "   }   ,     {   "   c   r   e   d   i   t   _   i   d   "   :     "   5   4   4   9   1   a   6   c   0   e   0   a   2   6   7   4   8   c   0   0   1   b   1   9   "   ,     "   d   e   p   a   r   t   m   e   n   t   "   :     "   a   r   t   "   ,     "   g   e   n   d   e   r   "   :     2   ,     "   i   d   "   :     1   4   3   5   0   ,     "   j   o   b   "   :     "   s   e   t     d   e   s   i   g   n   e   r   "   ,     "   n   a   m   e   "   :     "   r   i   c   h   a   r   d     f   .     m   a   y   s   "   }   ,     {   "   c   r   e   d   i   t   _   i   d   "   :     "   5   6   9   2   8   c   f   4   c   3   a   3   6   8   4   c   f   f   0   0   2   5   c   4   "   ,     "   d   e   p   a   r   t   m   e   n   t   "   :     "   p   r   o   d   u   c   t   i   o   n   "   ,     "   g   e   n   d   e   r   "   :     1   ,     "   i   d   "   :     2   0   2   9   4   ,     "   j   o   b   "   :     "   e   x   e   c   u   t   i   v   e     p   r   o   d   u   c   e   r   "   ,     "   n   a   m   e   "   :     "   l   a   e   t   a     k   a   l   o   g   r   i   d   i   s   "   }   ,     {   "   c   r   e   d   i   t   _   i   d   "   :     "   5   2   f   e   4   8   0   0   9   2   5   1   4   1   6   c   7   5   0   a   c   a   5   1   "   ,     "   d   e   p   a   r   t   m   e   n   t   "   :     "   c   o   s   t   u   m   e     &     m   a   k   e   -   u   p   "   ,     "   g   e   n   d   e   r   "   :     0   ,     "   i   d   "   :     1   7   6   7   5   ,     "   j   o   b   "   :     "   c   o   s   t   u   m   e     d   e   s   i   g   n   "   ,     "   n   a   m   e   "   :     "   m   a   y   e   s     c   .     r   u   b   e   o   "   }   ,     {   "   c   r   e   d   i   t   _   i   d   "   :     "   5   2   f   e   4   8   0   0   9   2   5   1   4   1   6   c   7   5   0   a   c   a   1   1   "   ,     "   d   e   p   a   r   t   m   e   n   t   "   :     "   c   a   m   e   r   a   "   ,     "   g   e   n   d   e   r   "   :     2   ,     "   i   d   "   :     1   8   2   6   5   ,     "   j   o   b   "   :     "   d   i   r   e   c   t   o   r     o   f     p   h   o   t   o   g   r   a   p   h   y   "   ,     "   n   a   m   e   "   :     "   m   a   u   r   o     f   i   o   r   e   "   }   ,     {   "   c   r   e   d   i   t   _   i   d   "   :     "   5   4   4   9   1   9   4   d   0   e   0   a   2   6   7   4   8   f   0   0   1   b   3   9   "   ,     "   d   e   p   a   r   t   m   e   n   t   "   :     "   a   r   t   "   ,     "   g   e   n   d   e   r   "   :     0   ,     "   i   d   "   :     4   2   2   8   1   ,     "   j   o   b   "   :     "   s   e   t     d   e   s   i   g   n   e   r   "   ,     "   n   a   m   e   "   :     "   s   c   o   t   t     h   e   r   b   e   r   t   s   o   n   "   }   ,     {   "   c   r   e   d   i   t   _   i   d   "   :     "   5   2   f   e   4   8   0   0   9   2   5   1   4   1   6   c   7   5   0   a   c   a   0   5   "   ,     "   d   e   p   a   r   t   m   e   n   t   "   :     "   c   r   e   w   "   ,     "   g   e   n   d   e   r   "   :     0   ,     "   i   d   "   :     4   2   2   8   8   ,     "   j   o   b   "   :     "   s   t   u   n   t   s   "   ,     "   n   a   m   e   "   :     "   w   o   o   d   y     s   c   h   u   l   t   z   "   }   ,     {   "   c   r   e   d   i   t   _   i   d   "   :     "   5   5   9   2   a   e   f   b   9   2   5   1   4   1   5   2   d   e   0   0   1   0   f   5   "   ,     "   d   e   p   a   r   t   m   e   n   t   "   :     "   c   o   s   t   u   m   e     &     m   a   k   e   -   u   p   "   ,     "   g   e   n   d   e   r   "   :     0   ,     "   i   d   "   :     2   9   0   6   7   ,     "   j   o   b   "   :     "   m   a   k   e   u   p     a   r   t   i   s   t   "   ,     "   n   a   m   e   "   :     "   l   i   n   d   a     d   e   v   e   t   t   a   "   }   ,     {   "   c   r   e   d   i   t   _   i   d   "   :     "   5   5   9   2   a   f   a   4   9   2   5   1   4   1   5   2   d   e   0   0   1   1   2   c   "   ,     "   d   e   p   a   r   t   m   e   n   t   "   :     "   c   o   s   t   u   m   e     &     m   a   k   e   -   u   p   "   ,     "   g   e   n   d   e   r   "   :     0   ,     "   i   d   "   :     2   9   0   6   7   ,     "   j   o   b   "   :     "   h   a   i   r   s   t   y   l   i   s   t   "   ,     "   n   a   m   e   "   :     "   l   i   n   d   a     d   e   v   e   t   t   a   "   }   ,     {   "   c   r   e   d   i   t   _   i   d   "   :     "   5   4   9   5   9   e   d   5   9   2   5   1   4   1   3   0   f   c   0   0   2   e   5   d   "   ,     "   d   e   p   a   r   t   m   e   n   t   "   :     "   c   a   m   e   r   a   "   ,     "   g   e   n   d   e   r   "   :     2   ,     "   i   d   "   :     3   3   3   0   2   ,     "   j   o   b   "   :     "   c   a   m   e   r   a     o   p   e   r   a   t   o   r   "   ,     "   n   a   m   e   "   :     "   r   i   c   h   a   r   d     b   l   u   c   k   "   }   ,     {   "   c   r   e   d   i   t   _   i   d   "   :     "   5   3   9   c   4   8   9   1   c   3   a   3   6   8   1   0   b   a   0   0   2   1   4   7   "   ,     "   d   e   p   a   r   t   m   e   n   t   "   :     "   a   r   t   "   ,     "   g   e   n   d   e   r   "   :     2   ,     "   i   d   "   :     3   3   3   0   3   ,     "   j   o   b   "   :     "   a   r   t     d   i   r   e   c   t   i   o   n   "   ,     "   n   a   m   e   "   :     "   s   i   m   o   n     b   r   i   g   h   t   "   }   ,     {   "   c   r   e   d   i   t   _   i   d   "   :     "   5   4   9   5   9   c   0   6   9   2   5   1   4   1   7   a   8   1   0   0   1   f   3   a   "   ,     "   d   e   p   a   r   t   m   e   n   t   "   :     "   v   i   s   u   a   l     e   f   f   e   c   t   s   "   ,     "   g   e   n   d   e   r   "   :     0   ,     "   i   d   "   :     1   1   3   1   4   5   ,     "   j   o   b   "   :     "   v   i   s   u   a   l     e   f   f   e   c   t   s     s   u   p   e   r   v   i   s   o   r   "   ,     "   n   a   m   e   "   :     "   r   i   c   h   a   r   d     m   a   r   t   i   n   "   }   ,     {   "   c   r   e   d   i   t   _   i   d   "   :     "   5   4   9   5   9   a   0   d   c   3   a   3   6   8   0   f   f   5   0   0   2   c   8   d   "   ,     "   d   e   p   a   r   t   m   e   n   t   "   :     "   c   r   e   w   "   ,     "   g   e   n   d   e   r   "   :     2   ,     "   i   d   "   :     5   8   1   8   8   ,     "   j   o

In [75]:
new_df['tags'].isnull().sum()
new_df['tags'] = new_df['tags'].fillna('')
new_df['tags'] = new_df['tags'].astype(str)

C:\Users\VENKATA PAVANI\AppData\Local\Temp\ipykernel_14052\2978390668.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].fillna('')
C:\Users\VENKATA PAVANI\AppData\Local\Temp\ipykernel_14052\2978390668.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].astype(str)

In [76]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000,stop_words='english')

In [85]:


cv.fit_transform(new_df['tags']).toarray()

ValueError: empty vocabulary; perhaps the documents only contain stop words

In [84]:
print('overview type:', type(movies.loc[0, 'overview']))
print('genres type:', type(movies.loc[0, 'genres']))
print('keywords type:', type(movies.loc[0, 'keywords']))
print('cast type:', type(movies.loc[0, 'cast']))
print('crew type:', type(movies.loc[0, 'crew']))
print('overview sample:', repr(movies.loc[0, 'overview'][:20]))
print('genres sample:', movies.loc[0, 'genres'][:10])
print('keywords sample:', movies.loc[0, 'keywords'][:10])
print('cast sample:', movies.loc[0, 'cast'][:10])
print('crew sample:', movies.loc[0, 'crew'][:10])
print('movie tags type before join:', type(movies.loc[0, 'tags']))
print('movie tags sample before join:', repr(movies.loc[0, 'tags'][:50]))
print('\nvalue counts by type for tags:', movies['tags'].apply(type).value_counts())
print('overview types:', movies['overview'].apply(type).value_counts())
print('genres types:', movies['genres'].apply(type).value_counts())
print('keywords types:', movies['keywords'].apply(type).value_counts())
print('cast types:', movies['cast'].apply(type).value_counts())
print('crew types:', movies['crew'].apply(type).value_counts())

overview type: <class 'list'>
genres type: <class 'list'>
keywords type: <class 'list'>
cast type: <class 'list'>
crew type: <class 'list'>
overview sample: ['In', 'the', '22nd', 'century,', 'a', 'paraplegic', 'Marine', 'is', 'dispatched', 'to', 'the', 'moon', 'Pandora', 'on', 'a', 'unique', 'mission,', 'but', 'becomes', 'torn']
genres sample: ['Action', 'Adventure', 'Fantasy']
keywords sample: ['cultureclash', 'future', 'spacewar']
cast sample: ['SamWorthington', 'ZoeSaldana', 'SigourneyWeaver']
crew sample: ['[', '{', '"', 'c', 'r', 'e', 'd', 'i', 't', '_']
movie tags type before join: <class 'list'>
movie tags sample before join: ['In', 'the', '22nd', 'century,', 'a', 'paraplegic', 'Marine', 'is', 'dispatched', 'to', 'the', 'moon', 'Pandora', 'on', 'a', 'unique', 'mission,', 'but', 'becomes', 'torn', 'between', 'following', 'orders', 'and', 'protecting', 'an', 'alien', 'civilization.', 'Action', 'Adventure', 'Fantasy', 'cultureclash', 'future', 'spacewar', 'SamWorthington', 'ZoeSaldana', 'SigourneyWeaver', '[', '{', '"', 'c', 'r', 'e', 'd', 'i', 't', '_', 'i', 'd', '"']

value counts by type for tags: tags
<class 'list'>    4806
Name: count, dtype: int64
overview types: overview
<class 'list'>    4806
Name: count, dtype: int64
genres types: genres
<class 'list'>    4806
Name: count, dtype: int64
keywords types: keywords
<class 'list'>    4806
Name: count, dtype: int64
cast types: cast
<class 'list'>    4806
Name: count, dtype: int64
crew types: crew
<class 'list'>    4806
Name: count, dtype: int64